---
format:
  revealjs: 
    theme: night
title: "Una introducción al entorno de BIBFRAME"
subtitle: "Un marco de datos vinculados para las bibliotecas"
date: 2024/10/21 - 2024/10/26
institute: Yale University
author: Timothy A. Thompson, Daniel Mugaburu
---

## ¿Quien soy? ¿Quienes somos?

- Nombre
- Puesto
- ¿Si tuviera que cantar en un karaoke, cuál canción elegiría para cantar?

## Reconocimiento de tierra

Los pueblos y naciones indígenas, incluyendo a los mohegan, los mashantucket pequot, los pequot orientales, los schaghticoke, los golden hill paugussett, los niantic, los quinnipiac y otros pueblos de habla algonquina, han administrado durante generaciones las tierras y los cursos de agua de lo que hoy es el estado de Connecticut.
Honramos y respetamos la relación duradera que existe entre estos pueblos y naciones y esta tierra.

## Pautas de participación

Los docentes estarán atentos a comentarios y reacciones por parte de los asistentes.
Consultaremos al grupo para solicitar reacciones verbales y no verbales.
Monitorearemos el chat y las reacciones para ver si hay comentarios o preguntas.
Los asistentes deben levantar la mano en Zoom para hacer preguntas o comentarios durante el taller.
Todos los asistentes pueden alertar al docente, directamente o por mensaje privado, si observan que alguien no está siendo escuchado.
Se puede entrar en contacto con los docentes para compartir comentarios.

## Pautas de conducta

Nosotros nos comprometemos a crear un ambiente acogedor, seguro y productivo para todos los participantes.
Eso requiere un espacio inclusivo y libre de acoso, donde se reconozca el valor inherente de cada persona.

## Pautas de conducta

Pedimos a los participantes que se comprometan a respetar las siguientes pautas de conducta:
Demostrar respeto. Evite interrumpir, criticar o menospreciar a los demás, sobre todo cuando describen sus propias experiencias vividas.
Dar espacio, ocupar espacio. Reconozca y comprenda la dinámica de poder que puede existir entre usted y los otros asistentes, y cómo eso puede influir en que los otros se sientan seguros para hablar.
Entender que la discusión es una conversación. Mantenga una actitud abierta para aprender y contemplar nuevas ideas.
Aceptar la divergencia. No es necesario llegar siempre a un consenso.

## Estructura del taller

Será un taller de 20 horas, o sea, 4 horas por día cada día de la semana.
Nos reuniremos de las 9:00 a la 1:00 cada día, horario de la Ciudad de México.
Tendremos un receso de 15 minutos por las mañanas para estirar las piernas o tomar un cafecito.
Cada día, tendremos una o dos actividades para poner en práctica los conceptos presentados durante el taller.
Dependiendo del número de asistentes, podemos realizar las actividades de manera individual o en salas virtuales para grupos pequeños.

## Estructura del taller
Día 1: Conceptos básicos de los datos abiertos vinculados.
Día 2: Vocabulario y modelo de BIBFRAME y su traducción en español.
Día 3: Introducción al editor Sinopia y una presentación invitada por la Mtra. Gloria Gonzalez (EBSO).
Día 4: Mini-taller sobre Wikidata con otra invitada especial, la Mtra. Mairelys Lemus-Rojas, Directora de Servicios de Metadatos en la Universidad de Brown.
Día 5: Trabajo práctico en el editor Sinopia, una plataforma de catalogación basada en tecnologías de datos vinculados.

## Plan para hoy
9:00–9:30: Introducciones y contexto
9:30–10:30: Conceptos básicos de los datos abiertos vinculados
10:30–10:45: Receso
10:45–11:00: Ontologías y el modelado de datos
11:00–12:45: Actividades prácticas
12:45–1:00: Resumen y discusión

## Datos

- ¿Qué son los datos abiertos vinculados?
- Analizaremos el término por parte, comenzando con datos.
- ¿Qué es un dato? Díganme ustedes cómo lo definirían.

## ¿Qué es un dato?
En la informática, según el Diccionario de la Real Academia Española, la palabra dato se define como:
Información dispuesta de manera adecuada para su tratamiento por una computadora.
Un dato es el átomo de la información.

## Ficha sacada del libro digital Documentation made easy

Ilustración basada en un video didáctico por Manu Sporny

Con el desarrollo constante de tecnologías de inteligencia artificial, se vuelve cada vez más posible extraer datos de contenido digitalizado.

## Extrayendo los datos

La extracción de datos facilita la búsqueda y la comprensión.
Leyendo los datos

La extracción de datos también facilita la comunicación y comprensión entre idiomas.
Traduciendo los datos

## La semántica de los datos

La extracción o minería de datos es una tecnología poderosa que puede traernos información, pero no necesariamente conocimiento.
Por sí solo, no logra distinguir entre datos y metadatos.
La estructura semántica de los datos sigue siendo invisible.

## Ilustración basada en un video didáctico por Manu Sporny

## Ilustración basada en un video didáctico por Manu Sporny

## Ilustración basada en un video didáctico por Manu Sporny

## Ilustración basada en un video didáctico por Manu Sporny

## Abiertos

Las 5 estrellas de los datos vinculados
Tim Berners-Lee, el inventor de la web, propuso un esquema de 5 estrellas para calificar los datos en la web.
					Los datos están disponibles en la web, en cualquier formato
		  			Datos estructurados, legibles por computadoras
					Disponibles en formatos abiertos (ej., CSV en vez de Excel)
					Publicados con estándares abiertos de la W3C (RDF, etc.)
					Todo lo anterior y se enlazan con otros datos abiertos

## Estándares

Las bases fundamentales de los datos abiertos enlazados son los estándares del Consorcio World Wide Web (W3C, por sus siglas en inglés). Ejemplos:
El Marco de Descripción de Recursos (RDF, por sus siglas en inglés)​
El Lenguaje de Ontologías Web (OWL, por sus siglas en inglés)​

## RDF

RDF es un modelo simple cuya estructura fundamental es la tripleta, en la cual tenemos una relación entre sujeto, predicado, y objeto.​
Las ideas de recurso e identificador son igualmente importantes.
RDF se basa en la misma tecnología que impulsa la propia web.

## RDF

En RDF, un recurso es algo sobre el cual se puede hacer declaraciones.
Un recurso puede identificarse por una dirección HTTP, permitiendo que se publiquen los datos en la web.
Así, pueden ser leídos tanto por humanos como por computadoras.

## RDF

La dirección ﻿https://dle.rae.es/dato identifica un recurso, que también podemos llamar de entidad. 
Una entidad tiene propiedades o atributos y puede relacionarse con otras entidades.

## RDF
Preguntas:
¿Qué tipo de entidad es la que se identifica por https://dle.rae.es/dato?
¿Cuáles son sus atributos?
¿Se relaciona con otras entidades?

## Vinculados

## RDF
RDF es un modelo orientado a grafos.
Cada nodo en el grafo (sujeto, objeto) es un recurso y se puede hacer declaraciones a su respeto.
Los nodos se conectan por aristas, que también son recursos.

## RDF
¿Cómo se expresa el modelo RDF de manera concreta?
Tenemos varias opciones de formato, o lo que se llama serializaciones.
Una de las más comunes se llama JSON-LD.


```
[
  {"@context": "http://schema.org/"},
  {
	"@type": [
  	    "DefinedTermSet",
             "Book"
	],
	"@id": "https://dle.rae.es/",
	"name": "Diccionario de la lengua española RAE - ASALE",
	"image": "https://dle.rae.es/app/doc/es/img/dle.jpg",
	"description": "Versión electrónica 23.5 del «Diccionario de la lengua española», obra lexicográfica académica por excelencia."
  },
  {
	"@type": "DefinedTerm",
	"@id": "https://dle.rae.es/dato",
	"name": "dato",
	"description": "1. m. Información sobre algo concreto que permite su conocimiento exacto o sirve para deducir las consecuencias derivadas de un hecho. A este problema le faltan datos numéricos.",
	"inDefinedTermSet": "https://dle.rae.es/"
  }
]
```

## En el código, podemos observar lo siguiente:

El contexto declarado es {"@context": "http://schema.org/"}, que significa que los predicados provienen del vocabulario de Schema.org.
El recurso https://dle.rae.es/dato tiene un tipo declarado de http://schema.org/DefinedTerm, o término definido.
Se relaciona con el recurso https://dle.rae.es/, que tiene un tipo declarado de http://schema.org/DefiniedTermSet, o conjunto de términos definidos.

## RDF

Cuando hablamos de la publicación de datos en RDF, otro concepto relevante es el concepto de nombre calificado.
Cada vocabulario de datos vinculados debe hospedarse en un dominio web y utilizar esta ubicación para identificar sus términos.​

Para no tener que escribir siempre la dirección completa, definimos prefijos para representar la parte repetida de una dirección.

Por ejemplo, el recurso http://schema.org/DefinedTerm puede abreviarse con el prefijo schema, de esta manera: `schema:DefinedTerm`.

De igual manera, el prefijo convencional para BIBFRAME (http://id.loc.gov/ontologies/bibframe/) es bf.

RDF

Los datos del DLE ganan 4, pero no 5 estrellas. ¿Saben decir por qué?

Datos de 

## Ontologías

¿Qué es una ontología?
En la informática, una ontología se define como:
Una definición formal de tipos, propiedades y relaciones entre entidades que realmente o fundamentalmente existen para un dominio de discurso en particular. (Wikipedia)

## RDF Schema

RDF también incluye una extensión enfocada en el modelado de datos.
RDF Schema (Esquema RDF, o RDFS, por sus siglas en inglés) sostiene la definición de modelos de datos para ​dominios de conocimiento específicos.
Utiliza conceptos de modelado de datos, como:
Clase (y subclase)
Propiedad (y subpropiedad)
Dominio
Rango
Individuo

## Clases
Según los estándares de la W3C:
Una clase define un grupo de individuos que [. . .] comparten algunas propiedades. Por ejemplo, Deborah y Frank son miembros de la clase Persona. Las clases pueden organizarse en una jerarquía de especialización. (W3C)
Las clases suelen escribirse con letra mayúscula (ej., Persona).

## Clases

Contribución
Ítem
Organización
Rol
Sello

## Propiedades
Según los estándares de la W3C:
Las propiedades pueden utilizarse para establecer relaciones entre individuos o de individuos a valores de datos. (W3C)
Las propiedades suelen escribirse con letra minúscula, o usando letra de caja camello (ej., normasDeDescripcion).

El nombre se debe a que las mayúsculas a lo largo de una palabra en camelCase se asemejan a las jorobas de un camello

## Propiedades

agente
contribución
fecha
marcado por (marcadoPor)
rol

## Individuos
Según los estándares de la W3C:
Los individuos son instancias de clases, y las propiedades pueden ser usadas para relacionar un individuo con otro. Por ejemplo, un individuo llamado Deborah puede ser descrito como una instancia de la clase Persona y la propiedad tieneEmpleador puede ser usada para relacionar el individuo Deborah con el individuo UniversidadDeStanford. (W3C)
Se puede decir también que los individuos son tipos o miembros de una clase.

## Individuos

Dominio y rango
Para las propiedades, puede definirse su dominio y su rango.
Según los estándares de la W3C:
Un dominio de propiedad reduce los individuos a los que puede aplicarse la propiedad. 
El rango de una propiedad reduce los individuos que una propiedad puede tener como su valor. (W3C)

Dominio
Rango
Propiedad

## Dominio y rango

Dominio
Propiedad
Rango
Contribución
rol
Agente
Congreso 
Familia 
Jurisdicción
Organización 
Persona
[Ninguno]
fecha
Literal

## Dominio y rango

Una propiedad puede tener como su rango (objeto) un recurso (acerca del cual se puede hacer declaraciones) o un literal. 
Por literal, se entiende un valor que puede ser una cadena de texto, o que puede seguir un formato de datos específico (como una fecha según la norma ISO 8601: "2022-08-08").
No se puede hacer más declaraciones acerca de objetos literales.

## Una ontología permite definir un modelo de datos, el cual:

permite describir los elementos de la realidad que intervienen en un problema dado y la forma en que se relacionan esos elementos entre sí. (Wikipedia)

## Por su parte, un vocabulario controlado es algo más simple. 

Define una lista de conceptos que pueden tener relaciones jerárquicas entre sí, pero que no representan una visión de mundo de manera explícita.

Sin embargo, se puede crear vocabularios controlados usando los estándares de RDF.
El estándar Simple Knowledge Organization System (SKOS, por sus siglas en inglés) se creó para proyectar tesauros y vocabularios controlados en RDF.
Ontologías y vocabularios controlados

Uno de los primeros pasos en la creación de una ontología es el desarrollo de preguntas de competencia.
Son preguntas que sirven para definir el alcance de la ontología y comprobar su eficacia después.
Con base en estas preguntas, uno puede empezar a construir un modelo de datos, definiendo clases, propiedades e individuos.

## ¿Cómo se hace una ontología?

Por ejemplo, en una ontología sobre comida y vino, uno podría plantear preguntas de competencia como las siguientes:
¿Qué características debo tener en cuenta al elegir un vino? 
¿Burdeos es un vino tinto o blanco? 
¿Cabernet Sauvignon va bien con mariscos?
¿Cuál es la mejor opción de vino para la carne asada? 
¿Qué características de un vino determinan si va bien con una comida? 
¿Cambia el aroma o cuerpo de un vino específico de acuerdo con el año de cosecha?
¿Cuáles fueron buenas añadas para el Napa Zinfandel? (Ontology 101)
¿Cómo se hace una ontología?

## Actividad

Desmontando un registro MARC 21

Desmontando un registro MARC 21
¿Hay un modelo de datos detrás de los formatos MARC 21 (datos bibliográficos, de autoridad, de fondos)?
¿Cuáles son las entidades y las relaciones presentes en un registro bibliográfico?

## Día 1: resumen
Los datos abiertos vinculados conforman un conjunto de tecnologías y estándares que procuran transformar los datos en conocimiento.
Construir una web de datos implica un compromiso con la producción de metadatos de calidad.
Así, plantea un desafío para las bibliotecas y organizaciones de herencia cultural.
Tenemos que comprometernos con la creación de metadatos abiertos, limpios y bien modelados, lo que demanda recursos y capacitación.

## Día 2

## Plan para hoy
9:00–9:15: Repaso del día anterior
9:15–9:45: Estudio de caso: LUX: Yale Collections Discovery
9:45–10:15: BIBFRAME: hacia un nuevo marco bibliográfico
10:15–10:30: Receso
10:30–12:45: ¿BIBFRAME en español?
12:45–1:00: Resumen y discusión

## En grupos pequeños, reflexionen sobre los temas y términos que vimos ayer.
Tomen notas en los documentos compartidos.
¿Cuáles fueron los conceptos y términos más importantes presentados?
¿Qué no quedó claro?
Eligen a alguien para presentar su resumen al grupo entero.
Grupo 1
Grupo 2
Grupo 3
Grupo 4

## Repaso del día anterior

## LUX: Yale Collections Discovery

Colecciones en Yale

Línea de tiempo

Línea de tiempo

Línea de tiempo

Línea de tiempo


Línea de tiempo

Línea de tiempo

LUX: Yale Collections Discovery

LUX: Yale Collections Discovery


Marcos de colaboración

Marcos de implementación

Marcos de implementación

Marcos de implementación

Alineación transversal de colecciones

Categorias transversales

Una visión en busca de un marco

Una visión en busca de un marco


Una visión en busca de un marco


## BIBFRAME

BIBFRAME en el universo de metadatos

Breve historia de BIBFRAME
maio de 2011: se anunció la creación de la iniciativa BIBFRAME
marzo de 2013: se lanzó BIBFRAME 1.0
2011: revisiones externas del modelo por expertos invitados
Reutilización de otros vocabularios
Enlaces a cosas, no cadenas de texto
Repensar los metadatos administrativos
abril de 2016: se lanzó BIBFRAME 2.0
2018: se empezó el proyecto piloto con BIBFRAME
2021: se lanzó el proyecto "BIBFRAME 100"
junio de 2021: se lanzó BIBFRAME 2.1

¿Cuál es el modelo de BIBFRAME?
BIBFRAME 1.0

¿Cuál es el modelo de BIBFRAME?
BIBFRAME 2.0

## Desde MARC 21 hacia BIBFRAME

"Linky" MARC: un enfoque de transición
100	1# $a Wolf, Robert S. $0 http://id.loc.gov/authorities/names/n97096089 
245	12 $a A tour through mathematical logic / $c Robert S. Wolf.
650	#0 $a Logic, Symbolic and mathematical. $0 http://id.loc.gov/authorities/subjects/sh85078115 
710	2# $a Mathematical Association of America. $0 http://id.loc.gov/authorities/names/n79105844 


## "Linky" MARC
380	## $a Novels $a Thrillers $2 lcgft $0 http://id.loc.gov/authorities/genreForms/gf2015026020 $0 http://id.loc.gov/authorities/genreForms/gf2014026571

370	## $c United States $g Paris (France) $2 naf $0 http://id.loc.gov/authorities/names/n78095330 $0 http://id.loc.gov/authorities/names/n79058874 


En 2021, se lanzó la versión 2.1 de BIBFRAME, añadiendo nuevas pautas y nuevos términos.
Se necesita completar y actualizar la traducción de BIBFRAME en español.
En grupos pequeños, revisen los términos y sus definiciones.
Para cada definición, hay una traducción automática que se necesita revisar y mejorar.
No es necesario ampliar las definiciones más allá del alcance de la definición original.
Cuando un grupo haya terminado con su hoja de cálculo, debe pasar a la hoja siguiente para que, al final, hayan visto todos los términos (clases y propiedades) en el vocabulario.

## Día 2: actividad

Grupo 1
Grupo 2
Grupo 3
Grupo 4
Vocabulario completo
## Día 2: actividad

## Día 2: resumen
BIBFRAME es una opción de ontología enfocada en el dominio bibliográfico.
Hay otras opciones de ontologías para el ámbito cultural, como RDA en RDF y Linked Art.
Es importante tener en mente los elementos culturales, institucionales y hasta políticos involucrados en la adopción y definición de nuevos modelos de datos.
A diferencia de RDA, BIBFRAME representa un marco más flexible y abierto. Se puede incluso proponer cambios a la ontología para que sean contemplados para versiones futuras.

## Día 3
