---
title: "Bibliografía"
page-navigation: true
---

# Recursos Generales sobre Web Semántica y Datos Enlazados

W3C Semantic Web Standards:

Sitio oficial del World Wide Web Consortium (W3C) que define los estándares para la Web Semántica, incluyendo RDF, OWL, y SPARQL.
https://www.w3.org/standards/semanticweb/
Linked Data - Tim Berners-Lee’s Linked Data Principles:

Artículo original de Tim Berners-Lee que introduce los principios de los Datos Enlazados.
https://www.w3.org/DesignIssues/LinkedData.html
RDF Primer (W3C):

Una guía completa del W3C para aprender sobre RDF, incluyendo conceptos básicos y ejemplos.
https://www.w3.org/TR/rdf11-primer/
SPARQL Query Language for RDF (W3C):

Recurso detallado sobre el lenguaje de consultas SPARQL para trabajar con datos RDF.
https://www.w3.org/TR/sparql11-query/


Linked Open Data Cloud:
Una visualización de conjuntos de datos enlazados en la Web de Datos Enlazados.
https://lod-cloud.net/


OWL 2 Web Ontology Language Primer (W3C):

Este es un tutorial que introduce OWL, el lenguaje estándar para desarrollar ontologías en la Web Semántica.
https://www.w3.org/TR/owl2-primer/


Ejemplo de ontologias:

BioPortal:

Un recurso del National Center for Biomedical Ontology (NCBO) que ofrece acceso a una gran colección de ontologías en el dominio de las ciencias biomédicas.
https://bioportal.bioontology.org/